nginx:
  image: nginx
  ports:
    - "80:80"
  volumes:
    - ./public:/public
    - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
php:
  build: .
  volumes:
    - ./public:/public